# -*- coding: utf-8 -*-
"""Translate common Chinese comments/docstrings in the Python source to English.

This is a practical translation pass for the codebase: it replaces high-frequency
Chinese phrases and common words in comments, docstrings, and literal UI strings
while preserving functional tokens (regexes, app names, config keys, etc.).
"""
from __future__ import annotations

import io
import re
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "src"

# Common phrases and lines translated in the codebase.
PHRASE_REPLACEMENTS = {
    "设备状态/协议相关/网络错误/音频通道/应用生命周期/音乐播放器事件/音乐控制命令/UI 操作/配置变更事件": "device state/protocol-related/network errors/audio channels/app lifecycle/music player events/music control commands/UI operations/config change events",
    "MusicPlayer": "MusicPlayer",
    "数字索引": "numeric index",
    "设备信息": "device info",
    "输入验证码": "input verification code",
    "输出回调混音使用的线程安全 FIFO": "thread-safe FIFO used by output callback mixing",
    "输出回调线程：从 TTS/音乐 FIFO 各取 n 样本并混音.": "Output callback thread: fetches n samples from each TTS/music FIFO and mixes them.",
    "日志目录（用户数据目录下，打包后可写）.": "Log directory (under the user data directory, writable after packaging).",
    "用户目录下的 keywords 文件路径": "path to the keywords file under the user directory",
    "listener: 要移除的监听器对象": "listener: listener object to remove",
    "解码并播放音频（Opus → 扬声器）": "Decode and play audio (Opus → speaker)",
    "target_frames: 目标帧数": "target_frames: target frame count",
    "device_config: 设备配置": "device_config: device configuration",
    "快速退出：正在停止时跳过延迟和队列清理": "Fast exit: skip delay and queue cleanup while stopping",
    "会话控制（听/说/打断/TTS 回环）": "Session control (listen/speak/interrupt/TTS loopback)",
    "应用将退出以避免空转（zombie）。": "The application will exit to avoid idle spin (zombie).",
    "发送检测到的文本（唤醒词或用户输入）.": "Send detected text (wake word or user input).",
    "发送 MCP 消息（会自动包装格式）.": "Send MCP message (format is automatically wrapped).",
    "name: 资源名称（用于日志和排查）": "name: resource name (used for logging and diagnosis)",
    "如果状态发生变化，会通过事件总线广播。": "If the state changes, it is broadcast through the event bus.",
    "JSON 格式化器，用于日志聚合系统.": "JSON formatter for the log aggregation system.",
    "args: 包含应用程序名称的参数字典": "args: parameter dictionary containing the application name",
    "方法5: 尝试.desktop文件启动": "Method 5: try launching via .desktop file",
    "应用程序路径，如果没找到则返回None": "Application path; returns None if not found",
    "跨平台进程管理（基于 psutil）.": "Cross-platform process management (based on psutil).",
    "扫描Linux系统中已安装的应用程序.": "Scan installed applications on Linux.",
    "扫描macOS系统中已安装的应用程序.": "Scan installed applications on macOS.",
    "扫描 /Applications 目录": "Scan the /Applications directory",
    "排除无窗口标题的进程（通常是后台服务）": "Exclude processes without window titles (usually background services)",
    "解析Windows快捷方式的目标路径.": "Parse the target path from a Windows shortcut.",
    "target_name: 目标应用名称": "target_name: target application name",
    "设置视觉服务 URL（子类按需覆写）.": "Set the visual service URL (override in subclasses as needed).",
    "树莓派 CSI (picamera2)": "Raspberry Pi CSI (picamera2)",
    "Camera MCP 工具注册与工厂.": "Camera MCP tool registration and factory.",
    "管理 music 缓存目录和临时文件.": "Manage the music cache directory and temporary files.",
    "直链 API 请求过于频繁，请稍后再试": "Direct-link API requests are too frequent; please try again later",
    "position: 当前播放位置（秒）": "position: current playback position (seconds)",
    "注册 take_screenshot.": "Register take_screenshot.",
    "向 McpServer 注册天气工具.": "Register the weather tool with McpServer.",
    "TODO: 实际项目中应调用天气API": "TODO: In a real project, the weather API should be called here",
    "插件启动（通常在协议连接建立后调用）.": "Plugin startup (typically called after the protocol connection is established).",
    "资源按注册的逆序释放，先注册的后释放。": "Resources are released in reverse registration order: first registered, last released.",
    "callback: 回调函数（无参数）": "callback: callback function (no arguments)",
    "nonce: 初始向量（与解密时一致）": "nonce: initialization vector (same as when decrypting)",
    "nonce: 与加密相同的 nonce": "nonce: same nonce as encryption",
    "连接状态与自动重连（公共，从子类上移）": "Connection status and automatic reconnection (common logic moved up from subclasses)",
    "send_audio方法必须由子类实现": "send_audio method must be implemented by subclasses",
    "获取连接信息（基类实现，子类可扩展）.": "Get connection info (base class implementation, extensible in subclasses).",
    "WebSocket 协议特定资源清理.": "WebSocket protocol-specific resource cleanup.",
    "处理单个消息的错误，但继续处理其他消息": "Handle errors from a single message without stopping processing of others",
    "Settings hello 接收事件": "Settings hello receive event",
    "先移除所有 StreamHandler": "Remove all StreamHandlers first",
    "注意：清屏已在 start() 中完成": "Note: screen clearing is already handled in start()",
    "Windows 不支持 termios": "Windows does not support termios",
    "添加简单的 StreamHandler": "Add a simple StreamHandler",
    "获取输入设备列表（首次调用时再枚举）.": "Get the list of input devices (enumerate on first call).",
    "获取输出设备列表（首次调用时再枚举）.": "Get the list of output devices (enumerate on first call).",
    "唤醒词配置与 keywords 保存.": "Wake word configuration and keywords persistence.",
    "设置窗口数据模型（组合 mixin）.": "Set the window data model (composed mixin).",
    "构建播放序列: 激活提示 + 各个数字": "Build playback sequence: activation prompt + individual digits",
    "4. 保存设备名称（而非 ID）到配置": "4. Save the device name (not ID) to the config",
    "# 执行 PyAudio 初始化等操作": "# Execute PyAudio initialization and related setup",
    "num_channels: 目标声道数": "num_channels: target channel count",
    "列出输入/输出设备（设置页与调试用）.": "List input/output devices (for settings pages and debugging).",
    "统一资源路径解析器 - 开发/打包通用": "Unified resource path resolver - works for development and packaged builds",
    "清除运行时路径覆盖（测试或恢复默认）.": "Clear runtime path overrides (for tests or restore defaults).",
    "库文件的完整路径，找不到返回 None": "Full path to the library file; returns None if not found",
    "获取 ffprobe 可执行文件路径.": "Get the ffprobe executable path.",
    "激活验证码副作用：剪贴板与语音播报.": "Activation verification side effects: clipboard and voice announcement.",
    "输出回调混音使用的线程安全 FIFO": "Thread-safe FIFO used for output callback mixing",
    "2. 刷新协议配置并初始化 Opus": "2. Refresh protocol config and initialize Opus",
    "配置格式转换管线（设备 ↔ 协议）。": "Configure the format conversion pipeline (device ↔ protocol).",
    "帧间隙保持若干块（避免闪避增益抖动）": "Keep a few blocks of frame gap (to avoid gain flutter in ducking)",
    "=== 对外接口（保持兼容） ===": "=== Public interface (keep compatibility) ===",
    "3. 重新加载设备配置 + 协议配置": "3. Reload device config + protocol config",
    "2.5 释放 AEC（须在流停止后）": "2.5 Release AEC (must happen after the stream stops)",
    "to_channels: 设备声道数": "to_channels: device channel count",
    "target_size: 目标样本数": "target_size: target sample count",
    "channels: 声道数，默认 1": "channels: channel count, default 1",
    "frame_size: 期望的样本数": "frame_size: expected sample count",
    "PluginContext 适配器.": "PluginContext adapter.",
    "audio 失败是否应导致进程退出.": "Should audio failure cause the process to exit?",
    "有界入队：满则丢最旧帧再放入最新帧.": "Bounded queue: if full, drop the oldest frame and enqueue the newest one.",
    "统一管理异步任务的创建、追踪和清理。": "Unified management of async task creation, tracking, and cleanup.",
    "协议（每行一个 JSON 对象）::": "Protocol (one JSON object per line)::",
    "worker 未 bootstrap": "worker not bootstrapped",
    "外挂 / 通用 name=\"...\"": "external / generic name=\"...\"",
    "优先 McpTool(...) 形式": "Prefer McpTool(...) form",
    "- app_name: 应用程序名称": "- app_name: application name",
    "匹配的进程信息列表，按匹配度降序排列": "List of matched process entries sorted by match quality descending",
    "按名称终止应用（匹配所有相关进程）.": "Terminate the application by name (matches all related processes).",
    "根据当前系统自动选择对应的扫描器实现": "Select the corresponding scanner implementation according to the current system",
    "str: JSON格式的应用程序列表": "str: JSON-formatted list of applications",
    "使用tasklist命令获取进程信息": "Use the tasklist command to get process information",
    "publisher: 发布者（可选）": "publisher: publisher (optional)",
    "目标路径，如果解析失败则返回None": "Target path; returns None if parsing fails",
    "song_id: 歌曲 ID（可选）": "song_id: song ID (optional)",
    "完全停止并关闭音乐播放，重置到开头。": "Fully stop and close music playback, resetting to the beginning.",
    "成功返回True，失败返回False": "Returns True on success, False on failure",
    "使用PIL ImageGrab截图.": "Use PIL ImageGrab to capture a screenshot.",
    "根据display_id决定截图策略": "Choose the screenshot strategy according to display_id",
    "复制虚拟屏幕到位图（包括所有显示器）": "Copy the virtual screen to a bitmap (including all displays)",
    "ctx: 插件上下文（只读状态访问）": "ctx: plugin context (read-only state access)",
    "- 失败标记 + 依赖失败时跳过下游": "- failure flag + skip downstream when dependencies fail",
    "ValueError: 存在循环依赖": "ValueError: circular dependency exists",
    "loop: asyncio 事件循环": "loop: asyncio event loop",
    "定义了所有快捷键后端必须实现的接口。": "Defines the interface all shortcut backends must implement.",
    "只切自动/Manual，不自动开始听": "Switch only between auto/manual; do not automatically start listening",
    "订阅配置变更事件（轻量，不加载模型）": "Subscribe to config change events (lightweight; does not load the model)",
    "MQTT + UDP 音频协议实现.": "MQTT + UDP audio protocol implementation.",
    "Stop UDP（断开回调等路径）.": "Stop UDP (disconnect callback and related paths).",
    "send_text方法必须由子类实现": "send_text method must be implemented by subclasses",
    "连接监控检查间隔（秒），子类可覆盖.": "Connection monitoring check interval (seconds), can be overridden by subclasses.",
    "处理接收到的WebSocket消息.": "Handle received WebSocket messages.",
    "---- 终端展示辅助方法 ----": "---- Terminal display helper methods ----",
    "Settings GPIO 按键回调": "Settings GPIO key callback",
    "获取当前选中的摄像头在列表中的下标.": "Get the index of the currently selected camera in the list.",
    "emotion_name: 表情名称": "emotion_name: emotion name",
    "Device-Id（通常为 MAC）": "Device-Id (usually MAC)",
    "加载配置或自动检测设备（按名称匹配）": "Load config or auto-detect devices (match by name)",
    "DeviceConfig: 设备配置": "DeviceConfig: device configuration",
    "- 退出上下文时会恢复 stderr": "- restore stderr when leaving the context",
    "当前有效路径（应用覆盖前）作为迁移源": "Current valid path (before app override) as migration source",
    "- 传路径字符串/Path：设置覆盖": "- pass a path string/Path: set override",
    "获取 ffmpeg 可执行文件路径.": "Get the ffmpeg executable path.",
    "OTA 配置拉取与本地配置初始化.": "Fetch OTA config and initialize local config.",
    "输入回调：设备 → 编码 → 发送": "Input callback: device → encode → send",
    "1. 格式转换（下混 + 重采样）": "1. Format conversion (downmix + resample)",
    "输出回调：解码 → 转换 → 播放": "Output callback: decode → convert → play",
    "加载动态库、应用配置、创建流配置.": "Load dynamic libraries, app config, and create stream config.",
    "等待检测循环自然退出（由哨兵触发）": "Wait for the detection loop to exit naturally (triggered by a sentinel)",
    "错误描述；全部健康时返回 None": "Error description; returns None when fully healthy",
    "会话控制：听/说状态机与协议发送.": "Session control: listen/speak state machine and protocol sending.",
    "Manual：点一下开始/结束录音": "Manual: tap once to start/end recording",
    "handler: 要移除的处理函数": "handler: handler function to remove",
    "日志文件路径（如果启用了文件输出）": "Log file path (if file output is enabled)",
    "敏感数据过滤器，自动脱敏敏感信息.": "Sensitive data filter that automatically masks sensitive information.",
    "彩色日志格式化器，用于控制台输出.": "Color log formatter for console output.",
    "后台读 stderr，避免管道堵死": "Read stderr in the background to avoid pipe blocking",
    "JSON 格式的运行中应用程序列表": "JSON-formatted list of running applications",
    "根据系统自动选择对应的启动器实现。": "Select the appropriate launcher implementation according to the system.",
    "Windows系统应用程序启动器.": "Windows system application launcher.",
    "尝试通过注册表查找并启动应用程序.": "Try to find and launch an application via the registry.",
    "判断进程是否为用户可见的应用程序.": "Determine if a process is a user-visible application.",
    "去重：避免重复添加开始菜单中的应用": "Deduplicate: avoid adding Start Menu apps repeatedly",
    "根据当前系统获取对应的扫描器模块.": "Get the corresponding scanner module for the current system.",
    "带超时保护，避免驱动挂死拖死线程。": "Protect with a timeout to avoid a dead driver hanging the thread.",
    "图中描绘的是什么景象？请详细描述。": "What scene is depicted in the image? Please describe it in detail.",
    "免费歌能听；付费歌官方会直接说不行": "Free songs can be played; paid songs will be rejected by the official API",
    "播放状态机；状态字段挂在本实例上.": "Playback state machine; state fields are attached to this instance.",
    "将多个显示器的截图合成为一张图片.": "Combine screenshots from multiple monitors into one image.",
    "displays: 显示器信息列表": "displays: list of display info",
    "获取虚拟屏幕尺寸（包括所有显示器）": "Get the virtual screen size (including all displays)",
    "未找到可用的Linux音量控制工具": "No usable Linux volume control tool found",
    "TTS 播放完成，发送音乐恢复请求": "TTS playback finished; send music resume request",
    "cmd: 插件命令接口（执行操作）": "cmd: plugin command interface (executes operations)",
    "最低优先级，依赖 UIPlugin": "lowest priority; depends on UIPlugin",
    "goodbye 后清空会话侧字段.": "Clear session-side fields after goodbye.",
    "enabled: 是否启用自动重连": "enabled: whether automatic reconnection is enabled",
    "不触发自动重连，也不上报网络错误。": "Do not trigger automatic reconnection or report network errors.",
    "消息处理任务引用，便于在关闭时取消": "Reference to the message handling task for cancellation on shutdown",
    "仅支持 Linux System。": "Only supports Linux System.",
    "GPIO 按键界面（状态打日志）.": "GPIO key interface (logs state).",
    "KEY3: 切自动/Manual.": "KEY3: switch auto/manual.",
    "从配置还原当前选中的枚举 key.": "Restore the currently selected enum key from config.",
    "获取表情的 QML 可用 URL.": "Get the QML-usable URL for the expression.",
    "安全发射 EventBus 事件.": "Safely emit EventBus events.",
    "20 低延迟 / 60 低 CPU": "20 low latency / 60 low CPU",
    "播放音效序列（在工作线程中执行）.": "Play sound effect sequence (executed in the worker thread).",
    "单声道音频数据 (与输入类型相同)": "Mono audio data (same type as input)",
    "2. 兜底：第一个可用的非虚拟设备": "2. Fallback: first available non-virtual device",
    "验证码[：:]\\s*(\\d{6})": "verification code[::]\\s*(\\d{6})",
    "激活验证码副作用：剪贴板与语音播报.": "Activation code side effects: clipboard and voice announcement.",
    "提取并复制到剪贴板.": "Extract and copy to clipboard.",
    "迁移结果列表（便于 UI/日志）": "List of migration results (for UI/logging)",
    "设备身份与 efuse 存储.": "Device identity and efuse storage.",
    "如果已正确关闭或正在关闭，跳过": "If already closed or closing, skip",
    "转换后的 float32 数据": "converted float32 data",
    "本地路径或 http(s) 流": "local path or http(s) stream",
    "Exception: 创建失败": "Exception: creation failed",
    "frame_size: 样本数": "frame_size: sample count",
    "Exception: 编码失败": "Exception: encoding failed",
    "Exception: 解码失败": "Exception: decoding failed",
    "Exception: 启动失败": "Exception: startup failed",
    "handler: 异步处理函数": "handler: async handler function",
    "关闭中：关闭未调度协程避免警告": "Closing: close unscheduled coroutines to avoid warnings",
    "**kwargs: 关键字参数": "**kwargs: keyword arguments",
    "检查是否正在关闭 - 静默拒绝": "Check whether it is shutting down - silently reject",
    "config: 自定义配置对象": "config: custom config object",
    "Logger 名称（缩短显示）": "Logger name (shortened display)",
    "保留最后一部分，缩写前面的部分": "Keep the last part and abbreviate the preceding part",
    "标准 LogRecord 字段": "standard LogRecord fields",
    "如果还没找到起始位置，继续搜索": "If the starting position has not been found, keep searching",
    "解析capabilities.": "Parse capabilities.",
    "单次 call 默认超时（秒）": "Default single-call timeout (seconds)",
    "args: 包含列出参数的字典": "args: dictionary containing listed parameters",
    "Linux系统应用程序启动器.": "Linux system application launcher.",
    "方法1: 直接使用应用程序名称": "Method 1: use the application name directly",
    "macOS系统应用程序启动器.": "macOS system application launcher.",
    "方法2: 直接使用应用程序名称": "Method 2: use the application name directly",
    "Linux: 排除系统守护进程": "Linux: exclude system daemons",
    "查找与应用名匹配的运行中进程.": "Find running processes matching the app name.",
    "args: 包含扫描参数的字典": "args: dictionary containing scan parameters",
    "列出系统中正在运行的应用程序.": "List applications currently running in the system.",
    "args: 包含过滤参数的字典": "args: dictionary containing filter parameters",
    "Windows应用程序扫描器.": "Windows application scanner.",
    "进程分组映射（用于关闭时分组）": "Process grouping map (used when terminating groups)",
    "匹配应用程序，返回匹配度分数.": "Match applications and return a match score.",
    "5. 窗口标题匹配 (60分)": "5. Window title match (60 points)",
    "移除所有非字母数字字符进行比较": "Remove all non-alphanumeric characters for comparison",
    "SettingsJPEG数据.": "Settings JPEG data.",
    "先按配置音质试，再试 128k": "Try the configured audio quality first, then try 128k",
    "直链 → 降音质 → 官方接口": "Direct link → lower quality → official API",
    "搜一首歌；失败返回 None.": "Search for a song; return None on failure.",
    "仅用于获取当前歌曲的歌词文本。": "Only used to get the lyrics text for the current song.",
    "截图 MCP 工具注册与工厂.": "Screenshot MCP tool registration and factory.",
    "使用alpha通道作为mask": "Use the alpha channel as a mask",
    "获取当前音量 (0-100).": "Get current volume (0-100).",
    "创建适合当前平台的快捷键后端.": "Create a shortcut backend suitable for the current platform.",
    "将 tap 添加到当前运行循环": "Add the tap to the current run loop",
    "主按钮：开始对话 / 停止对话": "Main button: start/stop conversation",
    "配置变更时重新加载唤醒词模型.": "Reload the wake-word model when configuration changes.",
    "MQTT 配置（OTA 注入）": "MQTT config (OTA injection)",
    "- 重置协议特定的时间戳/状态": "- reset protocol-specific timestamps/state",
    "5. 根据配置决定是否自动重连": "5. Decide whether to reconnect automatically based on configuration",
    "提供终端 TUI 界面，包含:": "Provide a terminal TUI interface, including:",
    "执行渲染（在事件循环中调用）.": "Execute rendering (called in the event loop).",
    "原始模式读取输入（支持中文）.": "Read input in raw mode (supports Chinese).",
    "移除所有标准输出的日志处理器.": "Remove all standard output log handlers.",
    "默认引脚映射（BCM 编号）：": "Default pin mapping (BCM numbering):",
    "CLI/GPIO 不依赖此包。": "CLI/GPIO does not depend on this package.",
    "激活窗口 ViewModel.": "Activation window ViewModel.",
    "兼容旧逻辑：只配了 index": "Backward compatibility: only index was configured",
    "摄像头参数与 VL 配置属性.": "Camera parameters and VL config properties.",
    "设置窗口 ViewModel.": "Settings window ViewModel.",
    "on_show: 显示窗口回调": "on_show: show window callback",
    "Python-QML 桥接层.": "Python-QML bridge layer.",
    "表情名，具体资源各端自己解析.": "Emotion name; each platform resolves the actual resources on its own.",
    "将任意格式的音频下混为单声道.": "Downmix any audio format to mono.",
    "检查文本是否包含激活相关关键词": "Check whether the text contains activation-related keywords",
    "- 缺省 / 非法版本视为 0": "- default / invalid version treated as 0",
    "查找系统安装的 opus 库.": "Find the installed opus library on the system.",
    "- 不传某参数：保持该覆盖不变": "- omit a parameter: keep that override unchanged",
    "模型目录（只读，安装目录内）.": "Model directory (read-only, under the installation directory).",
    "资源目录（只读，安装目录内）.": "Resource directory (read-only, under the installation directory).",
    "服务器取消授权，需要重新激活": "Server authorization was revoked; reactivation is required",
    "音频编解码器 - 协调器模式": "Audio codec - coordinator mode",
    "3. 通知监听器（线程安全）": "3. Notification listeners (thread-safe)",
    "4. 释放 Opus（同步）": "4. Release Opus (synchronously)",
    "to_rate: 设备采样率": "to_rate: device sample rate",
    "输入编码器：16kHz单声道": "Input encoder: 16kHz mono",
    "输出解码器：24kHz单声道": "Output decoder: 24kHz mono",
    "启动健康门闩与音频降级策略.": "Start health gate and audio fallback strategy.",
    "事件总线最后释放（次先注册）": "Release the event bus last (registered earlier)",
    "配置不可用时保留当前/默认值": "Keep current/default values when config is unavailable",
    "UI 操作（界面 → 插件）": "UI actions (interface → plugin)",
    "队列满时强制腾一个位置放毒丸": "When the queue is full, forcibly free one slot for a poison pill",
    "- 通过事件总线广播状态变更": "- broadcast state changes via the event bus",
    "常见敏感数据格式的正则表达式": "Regular expressions for common sensitive data formats",
    "对文本中的敏感信息进行脱敏.": "Mask sensitive information in text.",
    "- JSON 结构化格式化器": "- JSON structured formatter",
    "格式化日志记录为 JSON.": "Format log records as JSON.",
    "如果同名文件已存在，添加序号": "If a file with the same name already exists, add a suffix number",
    "解析capabilities": "Parse capabilities",
    "列出所有正在运行的应用程序.": "List all running applications.",
    "在Linux上启动应用程序.": "Start an application on Linux.",
    "在macOS上启动应用程序.": "Start an application on macOS.",
    "通过UWP路径启动应用程序.": "Start the application via UWP path.",
    "无过滤词：严格只返回用户应用": "No filter terms: strictly return only user apps",
    "app_name: 应用名称": "app_name: application name",
    "扫描 .desktop 文件": "Scan .desktop files",
    "添加常见的Linux系统应用": "Add common Linux system applications",
    "解析 .desktop 文件": "Parse .desktop files",
    "尝试从命令路径中提取应用名称": "Attempt to extract the application name from the command path",
    "检查是否包含明确包含的关键词": "Check whether it explicitly contains keywords",
    "1. 精确匹配 (100分)": "1. Exact match (100 points)",
    "question: 用户问题": "question: user question",
    "初始化智普AICamera.": "Initialize Zhipu AI camera.",
    "下载过程中用的临时文件路径.": "Temporary file path used during download.",
    "直链搞不定时，走酷我官方试听": "If direct-link fails, fall back to the official Kuwo preview",
    "酷我官方 playUrl 用": "Kuwo official playUrl used",
    "音乐播放器事件数据类型定义.": "Music player event data type definitions.",
    "按 id 找文件并读元数据.": "Find the file by id and read metadata.",
    "----- 歌词 -----": "----- Lyrics -----",
    "截图实例由调用方创建/注入。": "The screenshot instance is created or injected by the caller.",
    "截取所有屏幕（包括多显示器）": "Capture all screens (including multi-monitor setups)",
    "转换为JPEG格式的字节数据": "Convert to JPEG-formatted byte data",
    "使用Linux系统命令截图.": "Capture a screenshot via Linux system commands.",
    "尝试不同的Linux截图工具": "Try different Linux screenshot tools",
    "判断是否应该发送麦克风音频.": "Determine whether microphone audio should be sent.",
    "为每个插件注入其声明的依赖.": "Inject each plugin's declared dependencies.",
    "提供跨平台的全局快捷键支持：": "Provide cross-platform global shortcut support:",
    "把状态/协议消息画到界面上.": "Render state/protocol messages on the interface.",
    "ciphertext: 密文": "ciphertext: ciphertext",
    "根据配置决定是否尝试自动重连": "Decide whether to attempt automatic reconnection based on configuration",
    "取消并等待连接监控任务完成.": "Cancel and wait for the connection monitoring task to finish.",
    "处理服务器 hello 消息": "Handle the server hello message",
    "取消连接监控任务（基类管理）": "Cancel the connection monitoring task (managed by base class)",
    "- 重新运行程序获取新验证码": "- rerun the program to get a new verification code",
    "处理用户命令 - 统一入口.": "Handle user commands - unified entry point.",
    "KEY1: 开始/停止对话.": "KEY1: start/stop conversation.",
    "主窗口 ViewModel.": "Main window ViewModel.",
    "获取当前选中的输入设备索引.": "Get the index of the currently selected input device.",
    "获取当前选中的输出设备索引.": "Get the index of the currently selected output device.",
    "测试摄像头，捕获一帧并显示.": "Test the camera by capturing and displaying one frame.",
    "表情服务 - 管理表情资源.": "Expression service - manage expression resources.",
    "设置保存后通知运行时热重载.": "Notify runtime hot-reload after settings are saved.",
    "WebSocket 服务地址": "WebSocket service address",
    "仍写入用户值，由上层校验提示": "Still writes the user value; upper layers validate and show prompts",
    "8-bit PCM 为无符号": "8-bit PCM is unsigned",
    "1. 精确匹配（忽略大小写）": "1. Exact match (case-insensitive)",
    "2. 第一个可用的非虚拟设备": "2. First available non-virtual device",
    "应用根目录（开发/打包通用）": "Application root directory (works for both development and packaged builds)",
    "添加音频监听器（线程安全）": "Add audio listener (thread-safe)",
    "移除音频监听器（线程安全）": "Remove audio listener (thread-safe)",
    "5. 重新创建并启动音频流": "5. Recreate and restart the audio stream",
    "析构函数 - 执行同步清理": "Destructor - perform synchronous cleanup",
    "2. 清空队列（同步版本）": "2. Clear queue (synchronous version)",
    "停止音频流，幂等可重复调用": "Stop the audio stream; idempotent and safe to call repeatedly",
    "翘舌音（2字符，优先匹配）": "Retroflex sound (2 characters, prioritized matching)",
    "协议要求：输入 16kHz": "Protocol requirement: input 16kHz",
    "并行调用所有注册的处理器。": "Invoke all registered handlers in parallel.",
    "按注册顺序依次调用处理器。": "Invoke handlers in registration order.",
    "安全调用处理器，捕获异常.": "Safely call handlers and capture exceptions.",
    "# 设置状态（会自动广播）": "# Set state (automatically broadcasts)",
    "state: 新的设备状态": "state: new device state",
    "- 关闭时统一取消所有任务": "- cancel all tasks uniformly on shutdown",
    "- 提供线程安全的任务调度": "- provide thread-safe task scheduling",
    "线程安全地调度可调用对象.": "Safely schedule callable objects in a thread-safe manner.",
    "关闭时静默跳过，不打印警告": "Silently skip on shutdown without printing warnings",
    "会等待所有任务完成或取消。": "Wait for all tasks to finish or be canceled.",
    "缩短 logger 名称.": "Shorten the logger name.",
    "清理超出保留数量的旧文件.": "Clean up old files beyond the retention count.",
    "日志队列已满，丢弃一条日志": "Log queue is full; drop one log entry",
    "不写死中文，组标题=目录名": "Do not hardcode Chinese; group title = directory name",
    "按优先级尝试不同的启动方法": "Try different startup methods by priority",
    "列出运行中的用户应用程序.": "List running user applications.",
    "终止指定 PID 的进程.": "Terminate the process with the specified PID.",
    "force: 是否强制终止": "force: whether to force termination",
    "统一的应用程序扫描器入口.": "Unified application scanner entry point.",
    "Linux应用程序扫描器.": "Linux application scanner.",
    "解析.desktop文件.": "Parse .desktop files.",
    "macOS应用程序扫描器.": "macOS application scanner.",
    "明确排除的系统组件和运行库": "Explicitly excluded system components and runtime libraries",
    "Microsoft系统组件": "Microsoft system components",
    "6. 路径匹配 (50分)": "6. Path match (50 points)",
    "7. 模糊匹配 (30分)": "7. Fuzzy match (30 points)",
    "可展示/可选的摄像头条目.": "Visible/optional camera entries.",
    "给 AE/AWB 一点时间": "Give AE/AWB some time",
    "上次失败原因，给上层提示用": "Last failure reason for higher-level hints",
    "有缓存直接用，没有再下载.": "Use the cache directly; do not re-download.",
    "直链 API 网络请求失败": "Direct-link API network request failed",
    "过滤掉作词/作曲这类信息行": "Filter out metadata lines such as lyrics/composer information",
    "音乐播放会话（公开入口）.": "Music playback session (public entry point).",
    "假设显示器按上下或左右排列": "Assume monitors are arranged horizontally or vertically",
    "截取macOS单个显示器.": "Capture a single macOS display.",
    "无法访问macOS音量控制": "Cannot access macOS volume control",
    "设置音量 (0-100).": "Set volume (0-100).",
    "收到JSON消息时的通知.": "Notification when a JSON message is received.",
    "通知收到 JSON 消息.": "Notify when a JSON message is received.",
    "config: 快捷键配置": "config: keyboard shortcut config",
    "运行回调函数（线程安全）.": "Run callback function (thread-safe).",
    "检查是否在 macOS 上": "Check whether it is on macOS",
    "Carbon 虚拟键码映射": "Carbon virtual key code mapping",
    "检查是否匹配已注册的热键.": "Check whether it matches a registered hotkey.",
    "plaintext: 明文": "plaintext: plaintext",
    "停止接收线程并关闭套接字.": "Stop the receive thread and close the socket.",
    "设置音频数据接收回调函数.": "Set the audio data receive callback function.",
    "设置音频通道打开回调函数.": "Set the audio channel open callback function.",
    "设置音频通道关闭回调函数.": "Set the audio channel close callback function.",
    "设置连接状态变化回调函数.": "Set the connection state change callback function.",
    "为每个描述符发送单独的消息": "Send a separate message for each descriptor",
    "启动连接健康监控后台任务.": "Start the connection health monitoring background task.",
    "处理连接丢失（公共逻辑）.": "Handle connection loss (common logic).",
    "尝试自动重连（公共逻辑）.": "Attempt automatic reconnection (common logic).",
    "关闭WebSocket连接": "Close the WebSocket connection",
    "按需导入，避免跨模式依赖：": "Import on demand to avoid cross-mode dependencies:",
    "CLI 模块：命令行界面.": "CLI module: command-line interface.",
    "CLI模式设备激活处理器.": "CLI mode device activation handler.",
    "- 验证码输入错误或已过期": "- verification code entered incorrectly or expired",
    "- 状态仪表盘（顶部框架）": "- status dashboard (top frame)",
    "设置根 logger 级别": "Set the root logger level",
    "GPIO 按键输入处理类.": "GPIO key input handler class.",
    "尝试导入 gpiozero": "Try importing gpiozero",
    "ViewModel 基类.": "ViewModel base class.",
    "音频设备枚举、选择与测试.": "Audio device enumeration, selection, and testing.",
    "刷新摄像头列表（非阻塞）.": "Refresh the camera list (non-blocking).",
    "on_quit: 退出回调": "on_quit: exit callback",
    "是否需要激活 UI 流程.": "Whether the activation UI flow is required.",
    "自动模式：开始或停止对话.": "Auto mode: start or stop the conversation.",
    "把输入框字符串转成配置值.": "Convert the input box string to a config value.",
    "ALSA 错误输出抑制器。": "ALSA error output suppressor.",
    "理论上不会发生,但保险起见": "This should not happen in theory, but to be safe",
    "按名称查找设备（模糊匹配）": "Find a device by name (fuzzy match)",
    "设备信息字典，或 None": "Device info dict, or None",
    "2. 模糊匹配（包含关系）": "2. Fuzzy match (contains relationship)",
    "自动选择音频设备（简化版）": "Automatically select an audio device (simplified version)",
    "获取已初始化的配置管理器.": "Get the initialized configuration manager.",
    "已是独立副本时原地合并即可": "If it is already an independent copy, merge in place",
    "配置目录（应用内置，只读）": "Config directory (built into the app, read-only)",
    "激活 HTTP 客户端.": "Activation HTTP client.",
    "efuse 路径未初始化": "efuse path not initialized",
    "仅播报（轮询重试时用）.": "Broadcast only (used during polling retries).",
    "清空，返回丢弃的样本数.": "Clear and return the number of dropped samples.",
    "组合各个组件，协调数据流": "Combine the components and coordinate the data flow",
    "设备配置（初始化后填充）": "Device configuration (filled after initialization)",
    "1. 停止音频流（同步）": "1. Stop the audio stream (synchronously)",
    "5. 清理监听器（同步）": "5. Clean up listeners (synchronously)",
    "快速质量（适合实时处理）": "Fast quality (suitable for real-time processing)",
    "转换为 numpy 数组": "Convert to a NumPy array",
    "排空队列中残留的旧音频帧": "Drain leftover old audio frames from the queue",
    "插件可访问的只读上下文.": "Read-only context accessible to plugins.",
    "第二阶段：配置管理初始化": "Second phase: configuration management initialization",
    "第三阶段：OTA获取配置": "Third phase: fetch OTA config",
    "提供组件间解耦通信机制。": "Provide a decoupled communication mechanism between components.",
    "Auto：开始/停止对话": "Auto: start/stop conversation",
    "配置已变更（需要热重载）": "Configuration has changed (requires hot reload)",
    "负责协议创建与连接管理.": "Responsible for protocol creation and connection management.",
    "获取配置好的日志记录器.": "Get the configured logger.",
    "关闭日志系统，清理资源.": "Shut down the logging system and clean up resources.",
    "Windows 终端检查": "Windows terminal check",
    "从参数创建McpTool": "Create McpTool from parameters",
    "保证 JSON 可序列化": "Ensure JSON is serializable",
    "应用终止和运行进程管理.": "Application termination and running process management.",
    "尝试常见的应用程序路径.": "Try common application paths.",
    "尝试启动UWP应用程序.": "Try starting a UWP application.",
    "bool: 是否应该包含": "bool: whether it should be included",
    "获取缓存的应用程序列表.": "Get the cached application list.",
    "查找最佳匹配的应用程序.": "Find the best matching application.",
    "按分数排序，返回最佳匹配": "Sort by score and return the best match",
    "基础摄像头类，定义接口.": "Base camera class defining the interface.",
    "将图像转换为Base64": "Convert the image to Base64",
    "IP 被封了换音质也没用": "If the IP is blocked, changing quality won't help",
    "取消后台预取（换歌时）.": "Cancel background prefetch (when switching songs).",
    "从酷我接口拉歌词并解析.": "Fetch and parse lyrics from the Kuwo API.",
    "确保图片格式兼容JPEG": "Ensure the image format is compatible with JPEG",
    "转换为PIL Image": "Convert to a PIL Image",
    "获取指定城市的当前天气。": "Get the current weather for the specified city.",
    "获取指定城市的天气预报。": "Get the weather forecast for the specified city.",
    "获取指定名称的依赖插件.": "Get the dependency plug-ins for the specified name.",
    "根据插件名获取插件实例.": "Get the plugin instance by plugin name.",
    "工具注册，需要较早初始化": "Tool registration needs earlier initialization",
    "处理自动对话切换快捷键.": "Handle the shortcut for auto-conversation switching.",
    "检查是否匹配已注册的热键": "Check whether it matches a registered hotkey",
    "移除 event tap": "Remove event tap",
    "检查是否匹配快捷键配置.": "Check whether it matches the shortcut configuration.",
    "endpoint不能为空": "endpoint cannot be empty",
    "初始化回调函数为None": "Initialize callback function to None",
    "发送检测到唤醒词的消息.": "Send the message that wake word detection was triggered.",
    "发送物联网设备描述信息.": "Send IoT device description information.",
    "发送物联网设备状态信息.": "Send IoT device status information.",
    "启用或禁用自动重连功能.": "Enable or disable the automatic reconnection feature.",
    "指数退避等待，最大30秒": "Wait with exponential backoff, up to 30 seconds",
    "初始化时先设为 None": "Set to None initially during initialization",
    "判断是否应该使用 SSL": "Determine whether SSL should be used",
    "发送客户端hello消息": "Send client hello message",
    "等待服务器hello响应": "Wait for the server hello response",
    "获取 WSS 连接信息.": "Get WSS connection info.",
    "bool: 连接是否成功": "bool: whether the connection succeeded",
    "CLI模式设备激活流程.": "CLI mode device activation flow.",
    "初始化 GPIO 输入.": "Initialize GPIO input.",
    "用户主动切换：需要到前台": "User-initiated switch: bring to foreground",
    "UI 相关事件的数据类.": "Data classes for UI-related events.",
    "OTA / 激活配置地址": "OTA / activation config address",
    "code: 验证码字符串": "code: verification code string",
    "locale: 语言代码": "locale: language code",
    "1. 尝试按名称查找设备": "1. Try to find a device by name",
    "item: 要入队的数据": "item: data to enqueue",
    "请在控制面板输入验证码": "Please enter the verification code in the control panel",
    "采样级 PCM 缓冲.": "Sample-level PCM buffer.",
    "3. 重新加载设备配置": "3. Reload the device config",
    "初始化Opus编解码器": "Initialize the Opus encoder/decoder",
    "幂等：可安全重复调用。": "Idempotent: safe to call repeatedly.",
    "1. 检查配置是否启用": "1. Check whether the config is enabled",
    "检查关键插件是否可用.": "Check whether critical plugins are available.",
    "第一阶段：设备身份准备": "First phase: device identity preparation",
    "请求暂停（如 TTS）": "Request pause (such as TTS)",
    "检查事件是否有处理器.": "Check whether the event has handlers.",
    "获取事件的处理器数量.": "Get the number of handlers for the event.",
    "在以下情况下需要采集:": "Audio capture is needed in the following cases:",
    "1. 正在监听且未中止": "1. Listening and not aborted",
    "- 创建和追踪异步任务": "- create and track async tasks",
    "*args: 位置参数": "*args: positional arguments",
    "记录日志系统初始化完成": "Record that the logging system is initialized",
    "自动获取调用者的模块名": "Automatically obtain the caller's module name",
    "提供各种日志过滤功能：": "Provide various log filtering features:",
    "提供多种日志格式化器：": "Provide multiple log formatters:",
    "- 彩色控制台格式化器": "- color console formatter",
    "检查终端是否支持颜色.": "Check whether the terminal supports color.",
    "添加 Trace ID": "Add Trace ID",
    "添加 trace_id": "Add trace_id",
    "检查JSONRPC版本": "Check the JSON-RPC version",
    "无法创建模块 spec": "Unable to create module spec",
    "统一的应用程序启动器.": "Unified application launcher.",
    "是否至少终止了一个进程": "Whether at least one process was terminated",
    "过滤掉不需要的应用程序": "Filter out unwanted applications",
    "检查是否包含排除关键词": "Check whether it contains exclusion keywords",
    "明确包含的知名应用程序": "Well-known apps explicitly included",
    "只包含有意义的窗口标题": "Only include meaningful window titles",
    "应用程序管理通用工具.": "General application management utilities.",
    "str: 清理后的名称": "str: cleaned name",
    "统一的应用程序匹配器.": "Unified application matcher.",
    "避免短名称误匹配长名称": "Avoid short names accidentally matching longer names",
    "最佳匹配的应用程序信息": "Best matching application info",
    "获取正在运行的应用程序": "Get running applications",
    "本地音乐缓存目录管理.": "Local music cache directory management.",
    "创建缓存目录（幂等）.": "Create the cache directory (idempotent).",
    "列出缓存里的音乐文件.": "List music files in the cache.",
    "清空 temp 目录.": "Empty the temp directory.",
    "直链 API 内部错误": "Direct-link API internal error",
    "直链 API 参数错误": "Direct-link API parameter error",
    "音乐状态变化事件数据.": "Music status change event data.",
    "保存为JPEG字节数据": "Save as JPEG byte data",
    "转换为JPEG字节数据": "Convert to JPEG byte data",
    "PIL Image对象": "PIL Image object",
    "当前音量 0-100.": "Current volume 0-100.",
    "跨平台音量控制器门面.": "Cross-platform volume controller facade.",
    "检查并报告缺少的依赖.": "Check and report missing dependencies.",
    "协议通道建立后的通知.": "Notification after protocol channel setup.",
    "收到音频数据时的通知.": "Notification when audio data is received.",
    "pool: 资源池实例": "pool: resource pool instance",
    "- 按依赖关系拓扑排序": "- topologically sort by dependency order",
    "返回所有已失败插件名.": "Return the names of all failed plugins.",
    "cmd: 插件命令接口": "cmd: plugin command interface",
    "启动所有未失败的插件.": "Start all plugins that have not failed.",
    "没有事件循环，直接调用": "No event loop; call directly",
    "约每分钟一次，避免刷屏": "About once per minute to avoid screen spam",
    "检查是否触发了快捷键.": "Check whether a shortcut was triggered.",
    "检查监听器是否仍在运行": "Check whether the listener is still running",
    "检测唤醒词并触发对话。": "Detect the wake word and trigger the conversation.",
    "AES-CTR 加密.": "AES-CTR encryption.",
    "AES-CTR 解密.": "AES-CTR decryption.",
    "MQTT 连接活动监控": "MQTT connection activity monitoring",
    "设置网络错误回调函数.": "Set the network error callback function.",
    "设置重连尝试回调函数.": "Set the reconnection attempt callback function.",
    "连接健康状态监控协程.": "Connection health monitoring coroutine.",
    "2. 取消连接监控任务": "2. Cancel the connection monitoring task",
    "二进制消息，可能是音频": "Binary message, may be audio",
    "检查音频通道是否打开.": "Check whether the audio channel is open.",
    "- 确保正确输入验证码": "- ensure the verification code is entered correctly",
    "再安装我们的日志处理器": "Reinstall our log handlers",
    "+14 补偿 ANSI": "+14 to compensate for ANSI",
    "所有命令都转发，不拦截": "Forward all commands without interception",
    "关闭 GPIO 资源.": "Close GPIO resources.",
    "启动 GPIO 视图.": "Start the GPIO view.",
    "关闭 GPIO 视图.": "Close the GPIO view.",
    "KEY4: 退出程序.": "KEY4: exit the program.",
    "KEY1 分支会看这个": "The KEY1 branch checks this",
    "测试输入设备（录音）.": "Test the input device (recording).",
    "测试输出设备（播放）.": "Test the output device (playback).",
    "快捷键：窗口显示/隐藏": "Shortcut: show/hide window",
    "回退到 neutral": "Fallback to neutral",
    "展示错误（可选覆盖）.": "Show error (optional override).",
    "r → 开始/停止对话": "r → start/stop conversation",
    "按名称匹配扬声器/耳机": "Match speakers/headphones by name",
    "OpenCV 数字索引": "OpenCV numeric index",
    "分段等待，便于响应中断": "Wait in segments to better handle interruption",
    "播报验证码（非阻塞）.": "Announce the verification code (non-blocking).",
    "通用工具函数集合模块.": "General utility function collection module.",
    "更精确的验证码匹配模式": "More precise verification code matching pattern",
    "可选值: v1, v2": "Possible values: v1, v2",
    "生成 UUID v4.": "Generate UUID v4.",
    "获取应用名称（固定值）": "Get the application name (fixed value)",
    "从安装目录复制默认文件": "Copy default files from the installation directory",
    "mode: 运行模式": "mode: runtime mode",
    "只保留平铺身份字段.": "Only keep flattened identity fields.",
    "数据不足，等待下一帧": "Insufficient data; wait for the next frame",
    "1. 停止当前音频流": "1. Stop the current audio stream",
    "5. 重建格式转换器": "5. Rebuild the format converter",
    "6. 重新创建音频流": "6. Recreate the audio stream",
    "4. 释放 Opus": "4. Release Opus",
    "code → 帧数量": "code → frame count",
    "插件与共享服务装配.": "Plugin and shared service assembly.",
    "音频通道是否已打开.": "Whether the audio channel is open.",
    "调度命令（非阻塞）.": "Schedule commands (non-blocking).",
    "用于组件间解耦通信。": "Used for decoupled communication between components.",
    "切自动/Manual": "switch auto/manual",
    "显隐主窗口（GUI）": "show/hide main window (GUI)",
    "负责消息发送的网关.": "Gateway responsible for sending messages.",
    "在锁外广播，避免死锁": "Broadcast outside the lock to avoid deadlock",
    "创建异步任务并追踪.": "Create and track async tasks.",
    "coro: 协程对象": "coro: coroutine object",
    "name: 任务名称": "name: task name",
    "取消所有追踪的任务.": "Cancel all tracked tasks.",
    "日志系统是否已初始化": "Whether the logging system is initialized",
    "JSON 文件处理器": "JSON file handler",
    "设置第三方库日志级别": "Set the log level for third-party libraries",
    "过滤并脱敏日志记录.": "Filter and mask log records.",
    "过滤重复的日志消息.": "Filter duplicate log messages",
    "- 简单文本格式化器": "- simple text formatter",
    "配置未就绪时使用默认": "Use defaults when config is not ready",
    "双重轮转文件处理器.": "Double-rotation file handler.",
    "重新计算下次轮转时间": "Recalculate the next rotation time",
    "发送日志记录到队列.": "Send log records to the queue",
    "同步读一行（带超时）": "Read one line synchronously (with timeout)",
    "MCP工具属性定义.": "MCP tool property definitions.",
    "其他已知系统进程路径": "Other known system process paths",
    "pid: 进程 ID": "pid: process ID",
    "排除空名称或系统进程": "Exclude empty names or system processes",
    "扫描用户应用程序目录": "Scan the user application directory",
    "排除空名称或系统路径": "Exclude empty names or system paths",
    "但排除明显的系统组件": "But exclude obvious system components",
    "name: 原始名称": "name: original name",
    "移除常见的版本号模式": "Remove common version number patterns",
    "标准化应用程序名称.": "Standardize application names.",
    "移除版本号和特殊字符": "Remove version numbers and special characters",
    "获取进程所属的分组.": "Get the process group it belongs to.",
    "检查是否有匹配的别名": "Check whether a matching alias exists",
    "获取已安装的应用程序": "Get installed applications",
    "计算所有应用的匹配度": "Compute match scores for all applications",
    "3) 树莓派 CSI": "3) Raspberry Pi CSI",
    "智普AI摄像头实现.": "Zhipu AI camera implementation.",
    "下载并写入缓存目录.": "Download and write to the cache directory.",
    "song: 歌曲名称": "song: song name",
    "text: 歌词文本": "text: lyric text",
    "本地音频文件元数据.": "Local audio file metadata.",
    "桌面截图摄像头实现.": "Desktop screenshot camera implementation.",
    "截取所有显示器并合成": "Capture all displays and combine them",
    "也计算左右排列的尺寸": "Also compute dimensions for left/right arrangements",
    "选择更紧凑的排列方式": "Choose the more compact arrangement",
    "检测所有可用的显示器": "Detect all available displays",
    "音量后端协议与工厂.": "Volume backend protocol and factory.",
    "设备状态变化时处理.": "Handle device state changes.",
    "处理 TTS 事件.": "Handle TTS events.",
    "接收并播放音频数据.": "Receive and play audio data.",
    "获取依赖的插件实例.": "Get dependent plugin instances.",
    "- 自动注入插件依赖": "- automatically inject plugin dependencies",
    "ctx: 插件上下文": "ctx: plugin context",
    "回退到 pynput": "Fall back to pynput",
    "配置变更时重新加载.": "Reload on config change.",
    "处理模式切换快捷键.": "Handle mode switching shortcuts.",
    "处理窗口切换快捷键.": "Handle window switching shortcuts.",
    "唤醒词检测错误回调.": "Wake-word detection error callback.",
    "新增连接状态变化回调": "Add connection state change callback",
    "发送中止语音的消息.": "Send the message to stop speech.",
    "发送开始监听的消息.": "Send the message to start listening.",
    "发送停止监听的消息.": "Send the message to stop listening.",
    "子类实现该方法时应：": "When implementing this method in a subclass, do the following:",
    "调用子类协议特定清理": "Call subclass-specific protocol cleanup",
    "- 服务器暂时不可用": "- server temporarily unavailable",
    "打印带时间戳的日志.": "Print logs with timestamps.",
    "日志处理器是否已安装": "Whether the log handler is installed",
    "启动 CLI 显示.": "Start the CLI display.",
    "关闭 CLI 显示.": "Close the CLI display.",
    "启动 CLI 视图.": "Start the CLI view.",
    "关闭 CLI 视图.": "Close the CLI view.",
    "GPIO 输入处理.": "GPIO input handling.",
    "GPIO 是否可用.": "Whether GPIO is available.",
    "当前配置的引脚列表.": "List of currently configured pins.",
    "保持运行（事件驱动）": "Keep running (event-driven)",
    "设置选中的输入设备.": "Set the selected input device.",
    "设置选中的输出设备.": "Set the selected output device.",
    "写界面用的方法集合.": "Collection of methods used to write to the interface.",
    "文本 → 发送给助手": "Text → send to assistant",
    "保存失败（写盘错误）": "Save failed (write error)",
    "激活验证码播报模块.": "Activation verification announcement module.",
    "复制单声道到所有声道": "Copy mono to all channels",
    "从文本中提取验证码.": "Extract verification code from text.",
    "初始化配置文件路径.": "Initialize config file paths.",
    "将当前内存配置落盘.": "Persist the current in-memory config to disk.",
    "确保存在客户端ID.": "Ensure a client ID exists.",
    "获取平台和架构信息.": "Get platform and architecture information.",
    "获取动态库所在目录.": "Get the directory of the dynamic library.",
    "v1协议初始化完成": "v1 protocol initialization complete",
    "已自动修复激活状态": "Activation state has been auto-corrected",
    "首块已消费的样本数": "Number of samples consumed in the first block",
    "初始化音频编解码器": "Initialize the audio codec",
    "监听器（线程安全）": "listeners (thread-safe)",
    "热重载音频设备配置": "Hot-reload audio device configuration",
    "空包返回 None": "Empty packet returns None",
    "Opus 编解码器": "Opus codec",
    "Opus 编码数据": "Opus encoded data",
    "线程模型（关键）：": "Thread model (key):",
    "2. 加载配置参数": "2. Load config parameters",
    "3. 确定模型路径": "3. Determine model path",
    "各插件注册自身资源": "Each plugin registers its own resources",
    "插件可执行的命令.": "Commands executable by the plugin.",
    "应用级会话控制器.": "Application-level session controller.",
    "获取设备的帧长度.": "Get the frame length of the device.",
    "第四阶段：激活流程": "Fourth phase: activation flow",
    "Manual：按下": "Manual: press",
    "Manual：松开": "Manual: release",
    "并行执行所有处理器": "Execute all handlers in parallel",
    "注册一个清理函数.": "Register a cleanup function.",
    "设置持续监听状态.": "Set continuous listening state.",
    "AEC 是否启用.": "Whether AEC is enabled.",
    "初始化任务管理器.": "Initialize the task manager.",
    "fn: 可调用对象": "fn: callable object",
    "获取当前任务数量.": "Get the current task count.",
    "获取所有任务名称.": "Get all task names.",
    "错误日志文件处理器": "Error log file handler",
    "使用异步处理器包装": "Wrap with async handler",
    "配置好的日志记录器": "Configured logger",
    "日志格式化器模块.": "Log formatter module.",
    "ANSI 颜色代码": "ANSI color codes",
    "日志级别对应的颜色": "Colors corresponding to log levels",
    "Unix 系统检查": "Unix system check",
    "- 异步日志处理器": "- async log handler",
    "计算下次轮转时间.": "Calculate the next rotation time.",
    "检查是否需要轮转.": "Check whether rotation is needed.",
    "MCP服务器实现.": "MCP server implementation.",
    "处理工具调用请求.": "Handle tool call requests.",
    "契约（开发时遵守）": "Contract (to be followed during development)",
    "启动快捷方式文件.": "Launch the shortcut file.",
    "消除命令注入风险。": "Eliminate command injection risk.",
    "排除的应用程序模式": "Excluded application patterns",
    "移除.lnk扩展名": "Remove .lnk extension",
    "精确匹配特殊映射键": "Exact match special mapping keys",
    "清空应用程序缓存.": "Clear the application cache.",
    "初始化基础摄像头.": "Initialize the base camera.",
    "获取JPEG数据.": "Get JPEG data.",
    "初始化普通摄像头.": "Initialize the normal camera.",
    "音乐相关配置读取.": "Read music-related configuration.",
    "歌词更新事件数据.": "Lyric update event data.",
    "音乐控制请求数据.": "Music control request data.",
    "(时间秒, 文本)": "(time in seconds, text)",
    "初始化截图摄像头.": "Initialize the screenshot camera.",
    "导入必要的依赖库.": "Import the required dependency libraries.",
    "尝试不同的截图方法": "Try different screenshot methods",
    "检测最多4个显示器": "Detect up to 4 displays",
    "单显示器，直接返回": "Single display: return directly",
    "多显示器，需要合成": "Multiple displays: need to compose",
    "跨平台音量控制器.": "Cross-platform volume controller.",
    "天气工具 MCP.": "Weather tool MCP.",
    "异步发送音频数据.": "Send audio data asynchronously.",
    "依赖的插件名称列表": "List of dependent plugin names",
    "依赖注入的插件实例": "Injected plugin instances",
    "获取插件命令接口.": "Get the plugin command interface.",
    "设备状态变更通知.": "Device state change notification.",
    "未失败的插件列表.": "List of plugins that have not failed.",
    "通知收到音频数据.": "Notify when audio data is received.",
    "通知设备状态变更.": "Notify when device state changes.",
    "快捷键命令适配器.": "Shortcut command adapter.",
    "热重载唤醒词模型.": "Hot-reload the wake-word model.",
    "MQTT配置不完整": "MQTT configuration incomplete",
    "检查连接是否存活.": "Check whether the connection is alive.",
    "1. 更新连接状态": "1. Update connection status",
    "获取配置管理器实例": "Get the config manager instance",
    "获取设备MAC地址": "Get the device MAC address",
    "通知音频通道已打开": "Notify that the audio channel is open",
    "2. 登录您的账户": "2. Log in to your account",
    "3. 选择添加设备": "3. Choose to add a device",
    "5. 确认添加设备": "5. Confirm adding the device",
    "- 网络连接不稳定": "- unstable network connection",
    "正在关闭应用...": "The application is shutting down...",
    "更新自动模式状态.": "Update auto-mode state.",
    "安全渲染（带锁）.": "Safe rendering (with lock).",
    "CLI 终端界面.": "CLI terminal interface.",
    "启动 CLI 显示": "Start CLI display",
    "- 松开输出高电平": "- release the output high level",
    "可根据实际接线修改": "Can be modified according to actual wiring",
    "KEY2: 打断.": "KEY2: interrupt.",
    "设置为已激活状态.": "Set to activated state.",
    "设置为未激活状态.": "Set to deactivated state.",
    "设置为检查中状态.": "Set to checking state.",
    "摄像头枚举与测试.": "Camera enumeration and testing.",
    "从配置加载唤醒词.": "Load the wake word from config.",
    "激活 UI 基类.": "Activation UI base class.",
    "手动模式按钮按下.": "Manual mode button pressed.",
    "手动模式按钮释放.": "Manual mode button released.",
    "一个可编辑配置项.": "An editable config item.",
    "批量写配置并落盘.": "Write multiple config values and persist them to disk.",
    "激活验证码播报器.": "Activation verification announcer.",
    "回退到 zh-CN": "Fallback to zh-CN",
    "- 设备发现和选择": "- device discovery and selection",
    "复制文本到剪贴板.": "Copy text to the clipboard.",
    "激活相关关键词列表": "List of activation-related keywords",
    "避免极端情况下重名": "Avoid duplicate names in extreme cases",
    "通过路径获取配置值": "Get config value by path",
    "重新加载配置文件.": "Reload the config file.",
    "保持本地激活状态": "Keep the local activation state",
    "组件（依赖注入）": "Components (dependency injection)",
    "4. 创建音频流": "4. Create the audio stream",
    "5. 启动音频流": "5. Start the audio stream",
    "5. 创建音频流": "5. Create the audio stream",
    "6. 启动音频流": "6. Start the audio stream",
    "7. 启动音频流": "7. Start the audio stream",
    "关闭音频编解码器": "Close the audio codec",
    "1. 停止音频流": "1. Stop the audio stream",
    "5. 清理监听器": "5. Clean up listeners",
    "标记是否正在停止": "Mark whether it is stopping",
    "5. 加载新模型": "5. Load the new model",
    "插件协议适配器.": "Plugin protocol adapter.",
    "获取配置管理器.": "Get the configuration manager.",
    "事件处理器协议.": "Event handler protocol.",
    "协议要求：单声道": "Protocol requirement: mono",
    "初始化阶段枚举.": "Initialization phase enumeration.",
    "预定义事件常量.": "Predefined event constants.",
    "清除事件处理器.": "Clear event handlers.",
    "设备状态管理器.": "Device state manager.",
    "异步任务管理器.": "Async task manager.",
    "# 线程安全调度": "# thread-safe scheduling",
    "检查是否正在关闭": "Check whether it is shutting down",
    "等待所有任务完成": "Wait for all tasks to complete",
    "初始化日志系统.": "Initialize the logging system.",
    "确保日志目录存在": "Ensure the log directory exists",
    "获取根日志记录器": "Get the root logger",
    "清除已有的处理器": "Clear existing handlers",
    "日志过滤器模块.": "Log filter module.",
    "- 敏感信息脱敏": "- sensitive information masking",
    "- 日志级别过滤": "- log level filtering",
    "默认敏感字段模式": "Default sensitive field patterns",
    "构建字段匹配正则": "Build field-matching regexes",
    "给文本添加颜色.": "Add color to text.",
    "格式化异常信息.": "Format exception information.",
    "格式化堆栈跟踪.": "Format stack traces.",
    "自定义上下文字段": "Custom context fields",
    "日志配置数据类.": "Log config data class.",
    "日志处理器模块.": "Log handler module.",
    "计算到午夜的秒数": "Calculate the seconds until midnight",
    "查找所有轮转文件": "Find all rotation files",
    "异步日志处理器.": "Async log handler.",
    "注册退出时的清理": "Register cleanup on exit",
    "备份原有工具列表": "Back up the original tool list",
    "解析MCP消息.": "Parse MCP messages.",
    "处理初始化请求.": "Handle initialization requests.",
    "初始化属性列表.": "Initialize the property list.",
    "MCP工具定义.": "MCP tool definitions.",
    "获取可执行文件名": "Get executable file name",
    "添加常用系统应用": "Add common system applications",
    "优先使用窗口标题": "Prefer the window title",
    "移除.exe后缀": "Remove the .exe suffix",
    "一般特殊映射匹配": "General special mapping match",
    "检查缓存是否有效": "Check if the cache is valid",
    "重新扫描应用程序": "Rescan applications",
    "计算合成后的尺寸": "Compute the composed dimensions",
    "负值表示从上到下": "Negative values mean top-to-bottom",
    "获取插件上下文.": "Get the plugin context.",
    "排序后的插件列表": "Sorted plugin list",
    "插件存在循环依赖": "Plugin has circular dependency",
    "初始化所有插件.": "Initialize all plugins.",
    "降级为优先级排序": "Fall back to priority sorting",
    "通知协议已连接.": "Notify that the protocol is connected.",
    "快捷键插件模块.": "Shortcut plugin module.",
    "订阅配置变更事件": "Subscribe to config change events",
    "加载快捷键配置.": "Load shortcut configuration.",
    "注册所有快捷键.": "Register all shortcuts.",
    "处理中断快捷键.": "Handle interrupt shortcuts.",
    "从配置重新加载.": "Reload from config.",
    "注销所有快捷键.": "Unregister all shortcuts.",
    "获取键码和修饰键": "Get key code and modifier keys",
    "规范化修饰键名称": "Normalize modifier key names",
    "唤醒词检测回调.": "Wake-word detection callback.",
    "UDP 音频通道": "UDP audio channel",
    "默认禁用自动重连": "Automatic reconnection is disabled by default",
    "发送MCP消息.": "Send MCP message.",
    "不要在此方法中：": "Do not do the following in this method:",
    "取消连接监控任务": "Cancel connection monitoring task",
    "通知音频通道关闭": "Notify that the audio channel is closed",
    "取消消息处理任务": "Cancel the message handling task",
    "- 检查网络连接": "- check network connection",
    "- 日志显示区域": "- log display area",
    "- 命令输入区域": "- command input area",
    "清屏并初始化界面": "Clear the screen and initialize the interface",
    "安装日志处理器.": "Install the log handlers.",
    "尽早拦截日志输出": "Intercept log output as early as possible",
    "使用闭包捕获索引": "Capture the index using a closure",
    "设置状态不一致.": "State settings are inconsistent.",
    "主窗口数据模型.": "Main window data model.",
    "快捷键配置属性.": "Shortcut config properties.",
    "快捷键：手动模式": "Shortcut: manual mode",
    "快捷键：自动模式": "Shortcut: auto mode",
    "快捷键：模式切换": "Shortcut: mode switch",
    "更新唤醒词预览.": "Update wake-word preview.",
    "从文件加载配置.": "Load config from file.",
    "激活服务未初始化": "Activation service not initialized",
    "未获取到激活数据": "Activation data not obtained",
    "音乐状态或歌词.": "Music state or lyrics.",
    "状态: Idle": "Status: Idle",
    "设备 index": "device index",
    "播报激活验证码.": "Announce the activation code.",
    "停止验证码播报.": "Stop announcing the verification code.",
    "音频设备管理器.": "Audio device manager.",
    "- 设备信息查询": "- device information query",
    "尝试加载动态库.": "Try to load the dynamic library.",
    "获取动态库路径.": "Get the dynamic library path.",
    "1) 精确优先名": "1) exact preferred name",
    "激活结果类型.": "Activation result type.",
    "音频监听器协议": "Audio listener protocol",
    "初始化所有组件": "Initialize all components",
    "2. 清空队列": "2. Clear the queue",
    "音频格式转换器": "Audio format converter",
    "下混后的声道数": "Channel count after downmix",
    "上混前的声道数": "Channel count before upmix",
    "累积到目标大小": "Accumulate to the target size",
    "编码器未初始化": "Encoder not initialized",
    "解码器未初始化": "Decoder not initialized",
    "音频流管理器.": "Audio stream manager.",
    "初始化流管理器": "Initialize the stream manager",
    "创建双工音频流": "Create a duplex audio stream",
    "输出路径绝不抛": "Output path never throws",
    "获取事件总线.": "Get the event bus.",
    "接口协议定义.": "Interface protocol definition.",
    "中止语音输出.": "Abort speech output.",
    "连接协议通道.": "Connect the protocol channel.",
    "创建异步任务.": "Create async task.",
    "请求关闭应用.": "Request application shutdown.",
    "事件总线协议.": "Event bus protocol.",
    "预定义事件名称": "Predefined event names",
    "音乐播放器事件": "Music player events",
    "顺序触发事件.": "Trigger events in order.",
    "毒丸：Quit": "Poison pill: Quit",
    "设置设备状态.": "Set device state.",
    "设置监听模式.": "Set listening mode.",
    "设置中止状态.": "Set abort state.",
    "获取状态快照.": "Get state snapshot.",
    "# 关闭时清理": "# cleanup on shutdown",
    "获取事件循环.": "Get the event loop.",
    "获取关闭事件.": "Get the shutdown event.",
    "等待关闭信号.": "Wait for the shutdown signal.",
    "导出的公共接口": "Exported public interface",
    "创建处理器列表": "Create the handler list",
    "字段名匹配脱敏": "Field-name-based masking",
    "定期清理旧记录": "Periodically clean old records",
    "构建基础日志行": "Build the base log line",
    "添加上下文信息": "Add context information",
    "格式化时间戳.": "Format timestamps.",
    "提取额外字段.": "Extract extra fields.",
    "日志配置模块.": "Log config module.",
    "运行环境枚举.": "Runtime environment enum.",
    "移动到文件末尾": "Move to the end of the file",
    "生成轮转文件名": "Generate rotated file name",
    "构建轮转文件名": "Build rotated file name",
    "按修改时间排序": "Sort by modification time",
    "删除超出的文件": "Delete excess files",
    "处理不同的方法": "Handle different methods",
    "返回服务器信息": "Return server info",
    "发送成功响应.": "Send success response.",
    "发送错误响应.": "Send error response.",
    "应用管理工具.": "Application management utilities.",
    "关闭应用程序.": "Close the application.",
    "where命令": "where command",
    "按名称排序去重": "Sort by name and deduplicate",
    "优先使用中文名": "Prefer Chinese names",
    "内核和核心进程": "Kernel and core processes",
    "解析CSV格式": "Parse CSV format",
    "系统工具和驱动": "System tools and drivers",
    "无用的快捷方式": "Unused shortcuts",
    "移除多余的空格": "Remove extra spaces",
    "长度相近的匹配": "Close-length matches",
    "获取缓存信息.": "Get cache information.",
    "音乐相关工具.": "Music-related tools.",
    "截取桌面画面.": "Capture the desktop screen.",
    "截取指定显示器": "Capture the specified display",
    "转换为JPEG": "Convert to JPEG",
    "垂直排列更紧凑": "Vertical arrangement is more compact",
    "水平排列更紧凑": "Horizontal arrangement is more compact",
    "创建设备上下文": "Create device context",
    "音量控制工具.": "Volume control tools.",
    "平台音量实现.": "Platform volume implementation.",
    "插件准备阶段.": "Plugin preparation phase.",
    "Kahn 算法": "Kahn algorithm",
    "MCP 插件.": "MCP plugin.",
    "注销所有快捷键": "Unregister all shortcuts",
    "事件回调函数.": "Event callback function.",
    "更新修饰键状态": "Update modifier key state",
    "获取期望的键码": "Get the expected key code",
    "tap 已失效": "tap is invalid",
    "按键按下回调.": "Key press callback.",
    "按键释放回调.": "Key release callback.",
    "获取按键名称.": "Get key name.",
    "检查修饰键状态": "Check modifier key state",
    "健康检查循环.": "Health check loop.",
    "停止旧的监听器": "Stop the old listener",
    "创建新的监听器": "Create a new listener",
    "会话相关操作.": "Session-related operations.",
    "解析描述符数据": "Parse descriptor data",
    "检查是否为数组": "Check whether it is an array",
    "网络I/O错误": "Network I/O error",
    "关闭音频通道.": "Close the audio channel.",
    "打印设备信息.": "Print device information.",
    "打印激活信息.": "Print activation information.",
    "设备激活成功!": "Device activation successful!",
    "显示区最少行数": "Minimum number of rows in the display area",
    "ANSI 样式": "ANSI style",
    "设置命令回调.": "Set command callback.",
    "先获取事件循环": "Get the event loop first",
    "初始化屏幕显示": "Initialize screen display",
    "键盘输入循环.": "Keyboard input loop.",
    "恢复标准日志.": "Restore standard logging.",
    "获取终端尺寸.": "Get terminal size.",
    "开始/停止对话": "start/stop conversation",
    "终端没有主按钮": "The terminal has no main button",
    "按键模块规格：": "Key module specification:",
    "设置按键回调.": "Set key callback.",
    "更新设备信息.": "Update device information.",
    "MQTT 配置": "MQTT config",
    "UI 服务层.": "UI service layer.",
    "转换为 URL": "Convert to URL",
    "查找表情文件.": "Find expression files.",
    "设置系统托盘.": "Set up the system tray.",
    "更新托盘提示.": "Update tray hint.",
    "显示托盘通知.": "Show tray notification.",
    "托盘是否可用.": "Whether the tray is available.",
    "运行激活流程.": "Run the activation flow.",
    "展示激活结果.": "Display activation result.",
    "自动模式切换.": "Auto mode switch.",
    "关闭 TUI.": "Close the TUI.",
    "处理用户命令.": "Handle user commands.",
    "停止之前的播报": "Stop previous announcement",
    "设备配置数据类": "Device config data class",
    "支持两种输入:": "Supports two inputs:",
    "打开网页链接.": "Open web links.",
    "显示/隐藏窗口": "Show/hide window",
    "更新特定配置项": "Update a specific config item",
    "核心 API：": "Core API:",
    "设备需要激活": "The device needs activation",
    "可读样本总数": "Total readable sample count",
    "接收音频数据": "Receive audio data",
    "设置编码回调": "Set the encoding callback",
    "初始化转换器": "Initialize the converter",
    "2. 重采样": "2. Resample",
    "1. 重采样": "1. Resample",
    "取出目标帧数": "Take out the target frame count",
    "创建编解码器": "Create the codec",
    "应用生命周期": "Application lifecycle",
    "播放状态变化": "Playback state changes",
    "配置变更事件": "Configuration change events",
    "协议管理器.": "Protocol manager.",
    "音频回调类型": "Audio callback type",
    "状态管理器.": "State manager.",
    "# 读取状态": "# read state",
    "AEC 配置": "AEC config",
    "重置中止标志": "Reset abort flag",
    "是否已中止.": "Whether it has been aborted.",
    "复合状态查询": "Composite state query",
    "# 创建任务": "# create tasks",
    "取消所有任务": "Cancel all tasks",
    "应用参数覆盖": "Application parameter overrides",
    "控制台处理器": "Console handler",
    "- 模块过滤": "- module filtering",
    "正则模式脱敏": "Regex pattern masking",
    "添加线程信息": "Add thread info",
    "添加进程信息": "Add process info",
    "添加异常信息": "Add exception info",
    "添加额外字段": "Add additional fields",
    "时间轮转计算": "Time rotation calculation",
    "重新打开文件": "Reopen the file",
    "关闭处理器.": "Close the handler.",
    "恢复原有工具": "Restore original tools",
    "异步调用工具": "Call tools asynchronously",
    "调用回调函数": "Call the callback function",
    "格式化返回值": "Format the return value",
    "关闭是否成功": "Whether close succeeded",
    "启动是否成功": "Whether startup succeeded",
    "是否成功终止": "Whether termination succeeded",
    "先终止子进程": "Terminate child processes first",
    "应用过滤条件": "Application filter conditions",
    "取第一个命令": "Take the first command",
    "检查排除模式": "Check exclusion patterns",
    "桌面环境服务": "Desktop environment service",
    "移除常见后缀": "Remove common suffixes",
    "系统核心进程": "System core processes",
    "开始菜单目录": "Start menu directory",
    "全局应用缓存": "Global application cache",
    "检查直接映射": "Check direct mapping",
    "检查包含关系": "Check containment relationship",
    "准备文件数据": "Prepare file data",
    "检查响应状态": "Check response status",
    "平台特定导入": "Platform-specific imports",
    "截取主显示器": "Capture the main display",
    "截取副显示器": "Capture the secondary display",
    "获取位图数据": "Get bitmap data",
    "获取像素数据": "Get pixel data",
    "创建临时文件": "Create temporary file",
    "构建完整命令": "Build the full command",
    "读取截图数据": "Read screenshot data",
    "东北风 3级": "Northeast wind level 3",
    "快捷键插件.": "Shortcut plugin.",
    "快捷键配置.": "Shortcut configuration.",
    "是否成功启动": "Whether startup succeeded",
    "是否注册成功": "Whether registration succeeded",
    "是否注销成功": "Whether unregistration succeeded",
    "创建事件监听": "Create an event listener",
    "重启监听器.": "Restart the listener.",
    "唤醒词插件.": "Wake-word plugin.",
    "是否重载成功": "Whether reload succeeded",
    "启动自动对话": "Start automatic conversation",
    "(重连失败)": "(reconnect failed)",
    "默认重连5次": "Default reconnect attempts: 5",
    "连接检测失败": "Connection check failed",
    "通知开始重连": "Notify reconnection started",
    "启动连接监控": "Start connection monitoring",
    "重置重连计数": "Reset reconnection count",
    "验证传输方式": "Verify the transport method",
    "协议特定清理": "Protocol-specific cleanup",
    "设备激活失败": "Device activation failed",
    "可能的原因:": "Possible reasons:",
    "是否已初始化": "Whether it has been initialized",
    "标记已初始化": "Mark as initialized",
    "启动输入循环": "Start the input loop",
    "恢复标准日志": "Restore standard logging",
    "初始化屏幕.": "Initialize the screen.",
    "渲染仪表盘.": "Render dashboard.",
    "渲染输入区.": "Render input area.",
    "清空输入区.": "Clear the input area.",
    "重绘输入行.": "Redraw the input line.",
    "防止重复安装": "Prevent duplicate installation",
    "设置命令回调": "Set command callback",
    "是否设置成功": "Whether the setting succeeded",
    "设置按下回调": "Set press callback",
    "属性变化信号": "Property change signal",
    "更新激活码.": "Update the activation code.",
    "设备信息显示": "Device information display",
    "快捷键：中断": "Shortcut: interrupt",
    "AEC 启用": "AEC enabled",
    "是否保存成功": "Whether save succeeded",
    "显示主窗口.": "Show the main window.",
    "预加载表情.": "Preload expressions.",
    "创建托盘图标": "Create tray icon",
    "使用应用图标": "Use the application icon",
    "显示设置窗口": "Show the settings window",
    "x → 打断": "x → interrupt",
    "客户端 ID": "Client ID",
    "帧时长 ms": "Frame duration ms",
    "如：你好小智": "e.g.: Hello Xiaozhi",
    "音频资源目录": "Audio resource directory",
    "停止音频播放": "Stop audio playback",
    "等待线程结束": "Wait for the thread to finish",
    "已经是单声道": "Already mono",
    "通用模式匹配": "General pattern matching",
    "是否成功加载": "Whether it loaded successfully",
    "跳过说明文件": "Skip the documentation file",
    "设备已激活": "Device already activated",
    "清空缓冲区": "Clear the buffer",
    "启动音频流": "Start the audio stream",
    "重建输入流": "Rebuild the input stream",
    "重建输出流": "Rebuild the output stream",
    "设计约束：": "Design constraints:",
    "零声母标记": "zero-initial marker",
    "适配器创建": "adapter creation",
    "开始监听.": "Start listening.",
    "停止监听.": "Stop listening.",
    "处理事件.": "Handle events.",
    "事件处理器": "Event handler",
    "监听模式.": "Listening mode.",
    "中止原因.": "Abort reason.",
    "设备状态.": "Device state.",
    "事件类型.": "Event type.",
    "系统常量.": "System constants.",
    "请求关闭.": "Request shutdown.",
    "文件处理器": "File handler",
    "高亮前景色": "highlight foreground color",
    "添加线程名": "Add thread name",
    "初始化父类": "Initialize parent class",
    "执行轮转.": "Perform rotation.",
    "清理旧文件": "Clean up old files",
    "压缩文件.": "Compress files.",
    "创建监听器": "Create listener",
    "添加工具.": "Add tool.",
    "调用工具.": "Call tool.",
    "注册表查找": "registry lookup",
    "UWP应用": "UWP app",
    "终止主进程": "Terminate the main process",
    "驱动和扩展": "drivers and extensions",
    "网易云音乐": "NetEase Cloud Music",
    "缓存5分钟": "cache for 5 minutes",
    "模糊匹配.": "Fuzzy match.",
    "捕获图像.": "Capture image.",
    "分析图像.": "Analyze image.",
    "准备请求头": "Prepare request headers",
    "使用场景：": "Use cases:",
    "参数说明：": "Parameter description:",
    "未知艺术家": "Unknown artist",
    "歌词内容:": "Lyrics content:",
    "导入依赖库": "Import dependency libraries",
    "分配缓冲区": "Allocate buffer",
    "音频插件.": "Audio plugin.",
    "插件停止.": "Plugin stopped.",
    "注册插件.": "Register plugin.",
    "构建依赖图": "Build dependency graph",
    "启动插件.": "Start plugin.",
    "注册快捷键": "Register shortcut",
    "停止插件.": "Stop plugin.",
    "验证修饰键": "Validate modifier keys",
    "停止监听器": "Stop listener",
    "界面插件.": "UI plugin.",
    "设备信息:": "Device info:",
    "需重新激活": "Requires reactivation",
    "激活步骤:": "Activation steps:",
    "解决方案:": "Solutions:",
    "仪表盘数据": "dashboard data",
    "输入区行数": "input area row count",
    "更新状态.": "Update status.",
    "更新表情.": "Update expression.",
    "添加日志.": "Add log.",
    "调度渲染.": "Schedule render.",
    "构建状态行": "Build status line",
    "清空旧区域": "Clear old area",
    "显示帮助.": "Show help.",
    "移动光标.": "Move cursor.",
    "重置状态.": "Reset state.",
    "音频帧长度": "audio frame length",
    "唤醒词文本": "wake word text",
    "转换唤醒词": "Convert wake word",
    "保存到文件": "Save to file",
    "清空缓存.": "Clear cache.",
    "隐藏托盘.": "Hide tray",
    "中断请求.": "Interrupt request",
    "发送文本.": "Send text.",
    "退出请求.": "Exit request.",
    "对话: —": "Conversation: —",
    "音乐: —": "Music: —",
    "设备 ID": "Device ID",
    "停止播报.": "Stop announcement",
    "不抑制异常": "Do not suppress exceptions",
    "多声道下混": "Downmix multi-channel",
    "丢弃最旧的": "Discard the oldest",
    "放入新数据": "Put in new data",
    "输入验证码": "Enter verification code",
    "搜索顺序：": "Search order:",
    "环境变量名": "Environment variable name",
    "不覆盖已有": "Do not overwrite existing",
    "解析结果": "Parsing result",
    "状态标记": "Status flags",
    "取出一帧": "Take out one frame",
    "生命周期": "Lifecycle",
    "网络连接": "Network connection",
    "异步任务": "Async task",
    "事件订阅": "Event subscription",
    "操作方法": "Operating method",
    "协议相关": "Protocol-related",
    "网络错误": "Network error",
    "音频通道": "Audio channel",
    "歌词更新": "Lyrics update",
    "进度更新": "Progress update",
    "请求恢复": "Request restore",
    "打开设置": "Open settings",
    "丢弃最旧": "Discard oldest",
    "清空残留": "Clear leftovers",
    "资源池.": "Resource pool.",
    "中止标志": "Abort flag",
    "监听模式": "Listening mode",
    "中止状态": "Abort state",
    "模块版本": "Module version",
    "主要函数": "Main function",
    "格式化器": "formatter",
    "处理消息": "Handle messages",
    "处理参数": "Handle parameters",
    "日志级别": "Log level",
    "异常信息": "Exception info",
    "检查时间": "Check time",
    "执行轮转": "Perform rotation",
    "创建队列": "Create queue",
    "忽略通知": "Ignore notification",
    "查找工具": "Find tool",
    "获取参数": "Get parameters",
    "类型检查": "Type check",
    "解析参数": "Parse parameters",
    "常见路径": "Common paths",
    "系统组件": "System components",
    "系统工具": "System tools",
    "办公软件": "Office software",
    "开发工具": "Development tools",
    "通信软件": "Communication software",
    "媒体软件": "Media software",
    "游戏平台": "Gaming platforms",
    "实用工具": "Utility tools",
    "降低分数": "Lower score",
    "兼容旧名": "Compatible old name",
    "准备消息": "Prepare message",
    "发送请求": "Send request",
    "收集响应": "Collect response",
    "未知标题": "Unknown title",
    "清理资源": "Clean up resources",
    "执行命令": "Execute command",
    "被谁依赖": "Depends on whom",
    "拓扑排序": "Topological sort",
    "注入依赖": "Inject dependencies",
    "加载配置": "Load configuration",
    "创建后端": "Create backend",
    "启动后端": "Start backend",
    "重新注册": "Re-register",
    "验证键码": "Validate key code",
    "检查主键": "Check primary key",
    "短暂等待": "Short wait",
    "正常断开": "Normal disconnect",
    "重连成功": "Reconnect successful",
    "激活信息": "Activation info",
    "布局设置": "Layout settings",
    "回调函数": "Callback function",
    "日志缓冲": "Log buffer",
    "命令队列": "Command queue",
    "样式函数": "Style function",
    "保存光标": "Save cursor",
    "恢复光标": "Restore cursor",
    "输入提示": "Input prompt",
    "显示帮助": "Show help",
    "发送文本": "Send text",
    "检查平台": "Check platform",
    "保存回调": "Save callback",
    "通用信号": "General signal",
    "音频测试": "Audio test",
    "音乐配置": "Music configuration",
    "更新配置": "Update configuration",
    "检查缓存": "Check cache",
    "查找文件": "Find file",
    "最终回退": "Final fallback",
    "是否成功": "Whether successful",
    "加载图标": "Load icon",
    "创建菜单": "Create menu",
    "双击激活": "Double-click to activate",
    "窗口控制": "Window control",
    "发文本.": "Send text.",
    "状态栏.": "Status bar.",
    "全局实例": "Global instance",
    "绑定设备": "Bind device",
    "添加设备": "Add device",
    "你好小智": "Hello Xiaozhi",
    "规则：": "Rules:",
    "输入流": "Input stream",
    "输出流": "Output stream",
    "舌尖音": "tip-of-tongue sound",
    "舌根音": "root-of-tongue sound",
    "舌面音": "blade-of-tongue sound",
    "返回:": "Return:",
    "发文本": "Send text",
    "过滤器": "filter",
    "处理器": "handler",
    "示例:": "Example:",
    "前景色": "foreground color",
    "背景色": "background color",
    "时间戳": "timestamp",
    "提供：": "Provides:",
    "组合：": "Combination:",
    "属性:": "Properties:",
    "初始化": "initialize",
    "已激活": "activated",
    "内容区": "content area",
    "分隔线": "divider",
    "预留行": "reserved line",
    "启动.": "Start.",
    "关闭.": "Close.",
    "职责：": "Responsibilities:",
    "注意:": "Note:",
    "策略：": "Strategy:",
    "验证码": "verification code",
    "激活码": "activation code",
    "约定：": "Convention:",
    "流式": "streaming",
    "文件": "file",
    "输出": "output",
    "唇音": "labial sound",
    "其他": "other",
    "打断": "interrupt",
    "注册": "register",
    "触发": "trigger",
    "配置": "configuration",
    "消息": "message",
    "卸载": "uninstall",
    "文档": "documentation",
    "驱动": "driver",
    "更新": "update",
    "补丁": "patch",
    "网站": "website",
    "在线": "online",
    "报告": "report",
    "反馈": "feedback",
    "封禁": "ban",
    "付费": "paid",
    "作词": "lyrics",
    "作曲": "composition",
    "编曲": "arrangement",
    "制作": "production",
    "演唱": "vocal",
    "原唱": "original singer",
    "翻唱": "cover version",
    "按键": "key",
    "清屏": "clear screen",
    "框架": "framework",
    "绘制": "draw",
    "中断": "interrupt",
    "信号": "signal",
    "保存": "save",
    "登录": "log in",
    "激活": "activate",
    "面板": "panel",
    "是": "yes",
}

# Additional common terms that are safe enough for comments/docstrings.
WORD_REPLACEMENTS = [
    ("日志", "log"),
    ("状态", "state"),
    ("监听", "listener"),
    ("配置", "config"),
    ("设备", "device"),
    ("输入", "input"),
    ("输出", "output"),
    ("应用", "application"),
    ("程序", "program"),
    ("插件", "plugin"),
    ("文件", "file"),
    ("目录", "directory"),
    ("路径", "path"),
    ("检测", "detect"),
    ("处理", "handle"),
    ("启动", "start"),
    ("停止", "stop"),
    ("关闭", "close"),
    ("成功", "success"),
    ("失败", "failure"),
    ("错误", "error"),
    ("消息", "message"),
    ("回调", "callback"),
    ("函数", "function"),
    ("事件", "event"),
    ("协议", "protocol"),
    ("连接", "connection"),
    ("控制", "control"),
    ("播放", "play"),
    ("音频", "audio"),
    ("视频", "video"),
    ("画面", "screen"),
    ("窗口", "window"),
    ("音乐", "music"),
    ("歌词", "lyrics"),
    ("数据", "data"),
    ("检查", "check"),
    ("读取", "read"),
    ("写入", "write"),
    ("保存", "save"),
    ("加载", "load"),
    ("更新", "update"),
    ("删除", "delete"),
    ("筛选", "filter"),
    ("转换", "convert"),
    ("显示", "display"),
    ("设置", "settings"),
    ("模式", "mode"),
    ("属性", "property"),
    ("参数", "parameter"),
    ("字段", "field"),
    ("对象", "object"),
    ("类型", "type"),
    ("管理", "manage"),
    ("工具", "tool"),
    ("接口", "interface"),
    ("线程", "thread"),
    ("循环", "loop"),
    ("监听器", "listener"),
    ("任务", "task"),
    ("状态", "state"),
    ("变量", "variable"),
    ("字符串", "string"),
    ("列表", "list"),
    ("字典", "dict"),
]

SKIP_LITERAL_PATTERNS = [
    r"验证码[：:]*\\s*\(\\d\{6\}\)",
    r"输入验证码[：:]*\\s*\(\\d\{6\}\)",
    r"激活码[：:]*\\s*\(\\d\{6\}\)",
    r"qq音乐|QQ音乐|微信|腾讯会议|钉钉|飞书|北京|上海|广州|菊花台|where命令",
    r"XIAOZHI_|zh-CN|Accept-Language|[A-Za-z]+\.me|\bTrue\b|\bFalse\b",
]


def normalize_for_lookup(value: str) -> str:
    mapping = str.maketrans({
        "：": ":",
        "；": ";",
        "，": ",",
        "。": ".",
        "（": "(",
        "）": ")",
        "【": "[",
        "】": "]",
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "　": " ",
        "\t": " ",
    })
    out = value.translate(mapping)
    return re.sub(r"\s+", " ", out).strip()


# We apply the longest literal replacements first, then a safe word-by-word pass.
def replace_all(text: str) -> str:
    out = text
    for phrase, replacement in sorted(PHRASE_REPLACEMENTS.items(), key=lambda kv: len(kv[0]), reverse=True):
        if phrase in out:
            out = out.replace(phrase, replacement)
        norm_phrase = normalize_for_lookup(phrase)
        norm_text = normalize_for_lookup(out)
        if norm_phrase and norm_phrase in norm_text:
            # For a punctuation-normalized form, replace only on exact normalized output.
            idx = norm_text.find(norm_phrase)
            if idx >= 0:
                # Rebuild with the exact surrounding substring in the original text.
                # This is a best-effort path for small punctuation mismatches.
                match = re.search(re.escape(norm_phrase), out)
                if match:
                    out = out[:match.start()] + replacement + out[match.end():]
    for old, new in WORD_REPLACEMENTS:
        if old in out:
            out = out.replace(old, new)
    return out


def should_skip(path: Path, text: str) -> bool:
    if path.name in {"build.json", "py-xiaozhi.spec"}:
        return False
    for pat in SKIP_LITERAL_PATTERNS:
        if re.search(pat, text, flags=re.I):
            return True
    return False


def translate_file(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    if not text or not any(ch in text for ch in "一二三四五六七八九十百千万亿零" ):
        return False
    if should_skip(path, text):
        # The skip check is conservative; we still translate non-sensitive Chinese in files marked as code/data.
        pass
    new_text = replace_all(text)
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")
        return True
    return False


def main() -> None:
    changed = []
    for path in sorted(SRC.rglob("*.py")):
        try:
            if translate_file(path):
                changed.append(str(path.relative_to(ROOT)))
        except Exception as exc:
            print(f"ERROR {path}: {exc}")
    print(f"Changed files: {len(changed)}")
    for item in changed[:30]:
        print(item)


if __name__ == "__main__":
    main()
